contribution file alignment
Soluto/graphql-to-mongodb pull request #84
Opened 2022-07-10 19:20 UTC by nadavshlezz

Created the file - As part of contribution file alignment according to Soluto guidelines

2022-07-10 20:22 UTC, Mordech requested changes

2022-07-10 20:22 UTC, Mordech commented on CONTRIBUTING.md
> +Before you create a new issue, please do a search in (https://github.com/Soluto/graphql-to-mongodb/issues) to see if the issue or feature request has already been filed.
The space used between the link and the two makes the link merge with the word next to it resulting in a broken link.
<img width="356" alt="Screen Shot 2022-07-10 at 22 50 33" src="https://user-images.githubusercontent.com/71976177/178160921-de872142-0d23-4ebe-b958-6e9697a1bb8d.png">
```suggestion
Before you create a new issue, please do a search in [open issues](https://github.com/Soluto/graphql-to-mongodb/issues) to see if the issue or feature request has already been filed.
```

2022-07-11 05:41 UTC, nadavshlezz commented on CONTRIBUTING.md
> +Before you create a new issue, please do a search in (https://github.com/Soluto/graphql-to-mongodb/issues) to see if the issue or feature request has already been filed.
I'v test it in an online editor - now works
ill change it in the other PRs

<img width="1471" alt="Screen Shot 2022-07-11 at 8 38 26" src="https://user-images.githubusercontent.com/104714497/178196201-5b55264e-4f15-46b0-983f-db6879f073b0.png">
s

2022-07-11 05:49 UTC, Mordech approved these changes

2022-07-11 05:49 UTC, merged